### ISSUE TITLE
Remove old information about Zoom

### ISSUE THREAD

**Issue by kn1cht** [utelecon/utelecon.github.io#20]
`zoom/index.md`に、
> （現在は教職員のみ作成可能で，学生の方々は少々お待ち下さい）

という記述が残っています。3/24以降は学生にもZoomの招待が送られているはずですので、この部分を削除することを提案します。

https://github.com/utelecon/utelecon.github.io/blame/af35c4e74d7abd85349afb03afe0033e5ab1c7b5/zoom/index.md#L13-L14

**Comment by taura** [comment]
ご指摘ありがとうございました.
見落としていましたが今は直っています.
