### ISSUE TITLE
本文中に正確でない記述が含まれる

### ISSUE THREAD

**Issue by deep-dreamer** [utelecon/utelecon.github.io#32]
本文中に「PCまたはMac」「PC (WindowsやLinux), Macなどの環境」といった記述が見受けられますが、MacもPCであるため、これらは適切ではありません。

**Comment by kn1cht** [comment]
参考： [｢MacはPCではない｣はひと昔前の話 | ギズモード・ジャパン](https://www.gizmodo.jp/2016/02/mac_is_pc.html)

**Comment by kn1cht** [comment]
b16f5278c36d3a7021f6dfcbdb83c9b449b730d8 で修正されたと思われます．まだ残っているファイルもありますが，テスト用のファイルで公開ページからはリンクされていないようです．
